### PR TITLE
feat: default `github-token` to `github.token`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by hmarr** [comment]
Thanks, this seems to work. I'm not sure why we weren't using the default token before. It looks similar to #189 - @alejandrohdezma do you remember why you ended up closing that PR?

@MichaelDeBoey I'm happy to merge this, but there are a few changes on the `v2` branch you'll need to pull in. I did the merge locally but I don't have access to push to your repo. It's an easy merge though – the only conflicts are in the README (due to a change in the formatter's YAML whitespace preferences) and `main.ts` (due to another PR that I just merged, but you just need to copy the one line you changed over to the updated `run` function there).

**Comment by MichaelDeBoey** [comment]
@hmarr This should be OK to merge now

**Comment by hmarr** [comment]
Looks good, thanks. One more quick thing – I'm seeing a [big diff](https://github.com/hmarr/auto-approve-action/runs/7932219938?check_suite_focus=true#step:7:20) between the checked-in `dist/index.js` and the one CI is generating. Would you mind running `npm i && npm run build` and committing the results if they've changed?

**Comment by MichaelDeBoey** [comment]
@hmarr This should be OK to merge now

**Comment by hmarr** [comment]
Thanks! 🚀

**Pull request merged**
